### ISSUE TITLE
Zero counts in a year halts  get_citation_history(

### ISSUE THREAD

**Issue by JeffreyRacine** [jkeirstead/scholar#42] opened 2017-11-15 15:45 UTC
Greetings,

The following reveals get_citation_history is barfing on a year with zero counts... latest versions of R, RStudio, and all packages installed...

> library(scholar)
> library(ggplot2)
> cit <- get_citation_history('juybEFMAAAAJ&hl=en')
Error in data.frame(year = years, cites = vals) :
  arguments imply differing number of rows: 5, 4

Thanks!

**Comment by rudazhan** [comment] 2017-11-15 19:31
This is truly an issue of Google Scholar, which does not have a value for the missing year, instead of reporting 0. Nice catch.
But I think this is rather a rare case, so we may get away with it.

**Comment by JeffreyRacine** [comment] 2017-11-15 19:38
Many thanks for the kind and quick response,

I wonder how google scholar does it? If you see my colleagues profile it has a figure just like the ones scholar produces with the zero count displayed... see the upper right of the profile when viewed through a desktop browser...

https://scholar.google.com/citations?user=juybEFMAAAAJ&hl=en

Jeff

**Comment by rudazhan** [comment] 2017-11-15 20:09
To be honest, I don't really know how Google counted the citations. The `scholar` package simply pulls the histogram data from the page you see, and the year with no bar plotted is a missing value.
This might be a counting mistake, but could also be that Google assumes there should be no gap after the first year of citation.

**Comment by JeffreyRacine** [comment] 2017-11-15 20:10
No worries, and thanks for your contributions to the community!

**Comment by rudazhan** [comment] 2017-11-15 20:12
You're welcome.

*I'm migrating to this email. Please add it to your contacts.* 😊

ZHANG, Ruda
PhD candidate,
Department of Civil and Environmental Engineering
University of Southern California

**Comment by jefferis** [comment] 2017-11-15 20:28
Hmm. I think this is a duplicate of #29 fixed in this unmerged PR https://github.com/jkeirstead/scholar/pull/30

**Comment by jefferis** [comment] 2017-11-22 20:12
Closed as duplicate of #29. PR #30 has been merged to develop.

**Closed by jefferis** 2017-11-22 20:12 UTC
Labels: duplicate
