### ISSUE TITLE
get_publications return empty pubid

### ISSUE THREAD

**Issue by guillaumelobet** [jkeirstead/scholar#40] opened 2017-10-11 11:18 UTC
This is what I would like to do: 
- run `get_publications(author)`
- for each of the publications: `get_article_cite_history(author,pubid)`

However, `get_publications(author)` returns `void(0)` values in the `pubid` column, which means I cannot run `get_article_cite_history`. 

Any idea what is not working? The same script was working a couple of months ago, so would it be possible that it might be cause by the Google Scholar recent update?

**Comment by rudazhan** [comment] 2017-10-11 15:07
You may use the commit made by @GuangchuangYu here #39. The author is no longer maintaining this package.

**Comment by guillaumelobet** [comment] 2017-10-11 15:13
OK, thanks! I missed it somehow

**Comment by jefferis** [comment] 2017-11-22 20:13
Closed as duplicate of #41 fixed by #39, which should shortly be merged.

**Closed by jefferis** 2017-11-22 20:13 UTC
Labels: duplicate
