### ISSUE TITLE
get_publications maxes at 20

### ISSUE THREAD

**Issue by Cyade28** [jkeirstead/scholar#87] opened 2020-06-16 02:46 UTC
I have over 100 publications but the commands:
get_num_articles(id)
get_publications(id, pagesize=100)

only return me 20 results. Does anyone else have this issue?

**Comment by jefferis** [comment] 2021-07-13 18:20
Thanks @Cyade28. Sounds like a duplicate of #83 and I don't see this issue (now at least). If you still see a problem with the latest version of scholar, then please reopen with a reproducible example.

**Closed by jefferis** 2021-07-13 18:20 UTC
